### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by tombarys** [c3founder/ccc-roam-ocr#2]
Hi, the OCR stopped working in my Roam. Installed via Roam Depot. The message is `Granting wishes...` as usual and then shortly `OCR was unsuccessful.`

**Comment by tombarys** [comment]
Heard from other users that it does not work for them too... please respond.

**Comment by SChangVic** [comment]
Unfortunately, I just found this issue after I paid 20USD for mathpix API...And it does not work on my side either.

**Comment by tombarys** [comment]
Still not working 👎
